//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.Cargos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargos
    {
        public int IdCargo { get; set; }
        public string CodCargo { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
